controller_manager_ns: controller_manager
controller_list:
  - name: mra6/arm_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: 
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6


