mra6:
  arm_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints: 
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6

    constraints:
      goal_time: 0.5
      J1:
        goal: 0.1
      J2:
        goal: 0.1
      J3:
        goal: 0.1
      J4:
        goal: 0.1
      J5:
        goal: 0.1
      J6:
        goal: 0.1

    gains:
      J1: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      J2: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      J3: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      J4: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      J5: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      J6: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}




